//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PETHOTEL.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int o_id { get; set; }
        public Nullable<int> r_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public string o_pet_name { get; set; }
        public Nullable<int> o_pet_type { get; set; }
        public Nullable<int> o_pet_sex { get; set; }
        public string o_pet_content { get; set; }
        public string o_pet_image { get; set; }
        public Nullable<decimal> o_pet_price { get; set; }
        public Nullable<int> o_status { get; set; }
        public Nullable<System.DateTime> o_create_datetime { get; set; }
        public Nullable<System.DateTime> o_start_date { get; set; }
        public Nullable<System.DateTime> o_end_date { get; set; }

        
    }
}
