//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pethotel_manager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int c_id { get; set; }
        public string c_account { get; set; }
        public string c_password { get; set; }
        public string c_name { get; set; }
        public string c_address { get; set; }
        public string c_phone { get; set; }
        public string c_gmail { get; set; }
        public Nullable<System.Guid> c_valid_guid { get; set; }
        public Nullable<int> c_status { get; set; }
    }
}
