//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pethotel_manager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int i_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<int> r_id { get; set; }
        public Nullable<int> i_status { get; set; }
    }
}
